name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Ausführen, wenn auf den main-Branch gepusht wird
  workflow_dispatch: # Ermöglicht manuelles Starten des Workflows

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/devtoolbox

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devtoolbox:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Verify Docker Image
        run: |
          echo "Docker image successfully pushed to Docker Hub!"
          echo "Image: ${{ secrets.DOCKER_HUB_USERNAME }}/devtoolbox:latest"
