name: Build and deploy Angular SSR to Azure Web App - devtoolbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Build SSR Application
        run: npm run build:ssr

      - name: Zip Build Artifacts
        run: |
          mkdir output
          cp -r dist/devtoolbox/browser output/browser
          cp -r dist/devtoolbox/server output/server
          cp package.json output/
          cd output
          zip -r release.zip .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: output/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Unzip Build Artifacts
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'devtoolbox'
          slot-name: 'Production'
          package: .
