name: Build and deploy Angular SSR app to Azure Web App - devtoolbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build Angular SSR
        run: |
          npm install
          npm run build:ssr

      - name: Prepare deployment package
        run: |
          mkdir package
          cp -R dist/devtoolbox/browser/* package/
        working-directory: .

      - name: Zip artifact for deployment
        run: zip -r release.zip package

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_07F768CEF9DA411A85EF8649100104B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_18A957F43B2741DF9F7012E89C7E15CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_761415355285440D9C4DA785E0DF707A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'devtoolbox' # Dein Azure App Service Name
          slot-name: 'Production'
          package: './package' # Ordner, der nur die Build-Dateien enthält
        retry: 3
        timeout-minutes: 15
